-- V12: Granular ADMINISTRATOR permissions for ADMIN profile (beyond TODOS/VER).

INSERT OR IGNORE INTO adm_permissao_perfil (perfil_id, modulo, recurso, operacao, permitido)
SELECT p.id, 'ADMINISTRATOR', x.recurso, x.operacao, 1
FROM adm_perfil_acesso p
CROSS JOIN (
    SELECT 'APLICACAO' AS recurso, 'VER' AS operacao UNION ALL
    SELECT 'APLICACAO', 'CRIAR' UNION ALL
    SELECT 'APLICACAO', 'EDITAR' UNION ALL
    SELECT 'PARAMETROS', 'VER' UNION ALL
    SELECT 'PARAMETROS', 'CRIAR' UNION ALL
    SELECT 'PARAMETROS', 'EDITAR' UNION ALL
    SELECT 'PARAMETROS', 'APAGAR' UNION ALL
    SELECT 'LICENCAS', 'VER' UNION ALL
    SELECT 'LICENCAS', 'EDITAR' UNION ALL
    SELECT 'INTEGRACOES', 'VER' UNION ALL
    SELECT 'INTEGRACOES', 'EDITAR' UNION ALL
    SELECT 'FISCAL_AGT', 'VER' UNION ALL
    SELECT 'FISCAL_AGT', 'EDITAR' UNION ALL
    SELECT 'MONITOR', 'VER' UNION ALL
    SELECT 'INFRAESTRUTURA', 'VER' UNION ALL
    SELECT 'INFRAESTRUTURA', 'EDITAR' UNION ALL
    SELECT 'EMPRESAS', 'VER' UNION ALL
    SELECT 'EMPRESAS', 'CRIAR' UNION ALL
    SELECT 'EMPRESAS', 'EDITAR' UNION ALL
    SELECT 'EXERCICIOS', 'VER' UNION ALL
    SELECT 'EXERCICIOS', 'CRIAR' UNION ALL
    SELECT 'EXERCICIOS', 'EDITAR' UNION ALL
    SELECT 'UTILIZADORES', 'VER' UNION ALL
    SELECT 'UTILIZADORES', 'CRIAR' UNION ALL
    SELECT 'UTILIZADORES', 'EDITAR' UNION ALL
    SELECT 'UTILIZADORES', 'APAGAR' UNION ALL
    SELECT 'PERFIS', 'VER' UNION ALL
    SELECT 'PERFIS', 'CRIAR' UNION ALL
    SELECT 'PERFIS', 'EDITAR' UNION ALL
    SELECT 'PERFIS', 'APAGAR' UNION ALL
    SELECT 'SERIES', 'VER' UNION ALL
    SELECT 'SERIES', 'CRIAR' UNION ALL
    SELECT 'SERIES', 'EDITAR' UNION ALL
    SELECT 'AUDITORIA', 'VER' UNION ALL
    SELECT 'AUDITORIA', 'EXPORTAR' UNION ALL
    SELECT 'BACKUP', 'VER' UNION ALL
    SELECT 'BACKUP', 'CRIAR' UNION ALL
    SELECT 'RELATORIOS', 'VER' UNION ALL
    SELECT 'RELATORIOS', 'EXPORTAR'
) AS x
WHERE p.codigo = 'ADMIN';