-- V20: permissões granulares para as novas áreas do Administrator.

INSERT OR IGNORE INTO adm_permissao_perfil (perfil_id, modulo, recurso, operacao, permitido)
SELECT p.id, 'ADMINISTRATOR', x.recurso, x.operacao, 1
FROM adm_perfil_acesso p
CROSS JOIN (
    SELECT 'MOEDAS' AS recurso, 'VER' AS operacao UNION ALL
    SELECT 'MOEDAS', 'CRIAR' UNION ALL
    SELECT 'MOEDAS', 'EDITAR' UNION ALL
    SELECT 'MOEDAS', 'APAGAR' UNION ALL
    SELECT 'OPERACOES', 'VER' UNION ALL
    SELECT 'OPERACOES', 'CRIAR' UNION ALL
    SELECT 'OPERACOES', 'EDITAR' UNION ALL
    SELECT 'OPERACOES', 'APAGAR' UNION ALL
    SELECT 'SCHEDULER', 'VER' UNION ALL
    SELECT 'SCHEDULER', 'CRIAR' UNION ALL
    SELECT 'SCHEDULER', 'EDITAR' UNION ALL
    SELECT 'SCHEDULER', 'APAGAR' UNION ALL
    SELECT 'ALERTAS', 'VER' UNION ALL
    SELECT 'ALERTAS', 'EDITAR' UNION ALL
    SELECT 'SEGURANCA_AVANCADA', 'VER' UNION ALL
    SELECT 'SEGURANCA_AVANCADA', 'EDITAR' UNION ALL
    SELECT 'CERTIFICADOS', 'VER' UNION ALL
    SELECT 'CERTIFICADOS', 'EDITAR' UNION ALL
    SELECT 'DOCUMENTOS', 'VER' UNION ALL
    SELECT 'DOCUMENTOS', 'EDITAR' UNION ALL
    SELECT 'COMUNICACOES', 'VER' UNION ALL
    SELECT 'COMUNICACOES', 'EDITAR' UNION ALL
    SELECT 'PREFERENCIAS', 'VER' UNION ALL
    SELECT 'PREFERENCIAS', 'EDITAR' UNION ALL
    SELECT 'PERSONALIZACAO', 'VER' UNION ALL
    SELECT 'PERSONALIZACAO', 'EDITAR' UNION ALL
    SELECT 'SESSOES', 'VER' UNION ALL
    SELECT 'APLICACAO', 'EDITAR'
) AS x
WHERE p.codigo = 'ADMIN';
