-- V23__Add_FichaTecnica_Tables.sql (PostgreSQL version)

CREATE TABLE fichas_tecnicas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    produto_id BIGINT NOT NULL UNIQUE,
    observacoes TEXT,
    CONSTRAINT pk_fichas_tecnicas PRIMARY KEY (id),
    CONSTRAINT fk_fichas_tecnicas_on_produto FOREIGN KEY (produto_id) REFERENCES produtos (id)
);

CREATE TABLE fichas_tecnicas_itens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    ficha_tecnica_id BIGINT NOT NULL,
    produto_id BIGINT NOT NULL,
    quantidade DECIMAL(19, 4) NOT NULL,
    CONSTRAINT pk_fichas_tecnicas_itens PRIMARY KEY (id),
    CONSTRAINT fk_fichas_tecnicas_itens_on_ficha_tecnica FOREIGN KEY (ficha_tecnica_id) REFERENCES fichas_tecnicas (id),
    CONSTRAINT fk_fichas_tecnicas_itens_on_produto FOREIGN KEY (produto_id) REFERENCES produtos (id)
);
