-- V24__Add_Security_And_Profile_Tables.sql

-- Adicionar colunas à tabela users
ALTER TABLE users ADD COLUMN perfil_id BIGINT;
ALTER TABLE users ADD COLUMN mfa_secret VARCHAR(255);
ALTER TABLE users ADD COLUMN mfa_enabled BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE users ADD COLUMN ultimo_acesso TIMESTAMP WITHOUT TIME ZONE;

-- Criar tabela permissoes
CREATE TABLE permissoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    nome VARCHAR(255) NOT NULL UNIQUE,
    descricao TEXT,
    modulo VARCHAR(255) NOT NULL,
    CONSTRAINT pk_permissoes PRIMARY KEY (id)
);

-- Criar tabela perfis
CREATE TABLE perfis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    nome VARCHAR(255) NOT NULL UNIQUE,
    descricao TEXT,
    pai_id BIGINT,
    CONSTRAINT pk_perfis PRIMARY KEY (id),
    CONSTRAINT fk_perfis_on_pai FOREIGN KEY (pai_id) REFERENCES perfis (id)
);

-- Criar tabela de relacionamento perfil_permissoes
CREATE TABLE perfil_permissoes (
    perfil_id BIGINT NOT NULL,
    permissao_id BIGINT NOT NULL,
    CONSTRAINT pk_perfil_permissoes PRIMARY KEY (perfil_id, permissao_id),
    CONSTRAINT fk_perfil_permissoes_on_perfil FOREIGN KEY (perfil_id) REFERENCES perfis (id),
    CONSTRAINT fk_perfil_permissoes_on_permissao FOREIGN KEY (permissao_id) REFERENCES permissoes (id)
);

-- Criar tabela auditoria_acesso
CREATE TABLE auditoria_acesso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    user_id BIGINT,
    operacao VARCHAR(255) NOT NULL,
    recurso VARCHAR(255),
    ip VARCHAR(255),
    detalhes TEXT,
    sucesso BOOLEAN NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_auditoria_acesso PRIMARY KEY (id),
    CONSTRAINT fk_auditoria_acesso_on_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- Adicionar foreign key para perfil_id na tabela users
ALTER TABLE users ADD CONSTRAINT fk_users_on_perfil FOREIGN KEY (perfil_id) REFERENCES perfis (id);
