-- Adiciona campos faltantes à tabela de clientes (PostgreSQL)
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS data_nascimento DATE;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS genero VARCHAR(32);
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS estado_civil VARCHAR(32);
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS passaporte VARCHAR(64);
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS provincia VARCHAR(255);
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS municipio VARCHAR(255);
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS categoria_cliente VARCHAR(255);
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS limite_credito DECIMAL(19, 2) DEFAULT 0.00;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS estatuto VARCHAR(32);
