-- V48: permissões para todas as capacidades do Centro Completo da Plataforma.
INSERT OR IGNORE INTO adm_permissao_perfil (perfil_id, modulo, recurso, operacao, permitido)
SELECT p.id, 'ADMINISTRATOR', x.recurso, x.operacao, 1
FROM adm_perfil_acesso p
CROSS JOIN (
    SELECT 'OPERACOES' recurso,'EXECUTAR' operacao UNION ALL
    SELECT 'OPERACOES','RETRY' UNION ALL
    SELECT 'SCHEDULER','EXECUTAR' UNION ALL
    SELECT 'ALERTAS','CRIAR' UNION ALL
    SELECT 'ALERTAS','APAGAR' UNION ALL
    SELECT 'DOCUMENTOS','CRIAR' UNION ALL
    SELECT 'DOCUMENTOS','APAGAR' UNION ALL
    SELECT 'COMUNICACOES','CRIAR' UNION ALL
    SELECT 'COMUNICACOES','EXECUTAR' UNION ALL
    SELECT 'COMUNICACOES','APAGAR' UNION ALL
    SELECT 'PREFERENCIAS','CRIAR' UNION ALL
    SELECT 'PERSONALIZACAO','CRIAR' UNION ALL
    SELECT 'PERSONALIZACAO','APAGAR' UNION ALL
    SELECT 'BASE_DADOS','VER' UNION ALL
    SELECT 'BASE_DADOS','CRIAR' UNION ALL
    SELECT 'BASE_DADOS','EDITAR' UNION ALL
    SELECT 'BASE_DADOS','EXECUTAR' UNION ALL
    SELECT 'LISTAGENS','VER' UNION ALL
    SELECT 'LISTAGENS','CRIAR' UNION ALL
    SELECT 'LISTAGENS','EDITAR' UNION ALL
    SELECT 'LISTAGENS','APAGAR' UNION ALL
    SELECT 'MAPAS','VER' UNION ALL
    SELECT 'MAPAS','CRIAR' UNION ALL
    SELECT 'MAPAS','EDITAR' UNION ALL
    SELECT 'MAPAS','APAGAR'
) x
WHERE p.codigo='ADMIN';
