-- V49: permissões dos motores runtime do Centro da Plataforma.
INSERT OR IGNORE INTO adm_permissao_perfil (perfil_id, modulo, recurso, operacao, permitido)
SELECT p.id, 'ADMINISTRATOR', x.recurso, x.operacao, 1
FROM adm_perfil_acesso p
CROSS JOIN (
    SELECT 'EXTENSIBILIDADE' recurso,'VER' operacao UNION ALL
    SELECT 'EXTENSIBILIDADE','EXECUTAR' UNION ALL
    SELECT 'LISTAGENS','EXECUTAR' UNION ALL
    SELECT 'MAPAS','EXECUTAR' UNION ALL
    SELECT 'PESQUISA_GLOBAL','EXECUTAR' UNION ALL
    SELECT 'EVENTOS','VER' UNION ALL
    SELECT 'EVENTOS','CRIAR' UNION ALL
    SELECT 'EVENTOS','EXECUTAR' UNION ALL
    SELECT 'NOTIFICACOES','VER' UNION ALL
    SELECT 'CALENDARIO','VER' UNION ALL
    SELECT 'CALENDARIO','CRIAR' UNION ALL
    SELECT 'DASHBOARD','VER' UNION ALL
    SELECT 'DASHBOARD','CRIAR' UNION ALL
    SELECT 'DASHBOARD','EXECUTAR' UNION ALL
    SELECT 'ANEXOS','VER' UNION ALL
    SELECT 'ANEXOS','CRIAR' UNION ALL
    SELECT 'ANEXOS','APAGAR' UNION ALL
    SELECT 'LICENCA','VER' UNION ALL
    SELECT 'LICENCA','EDITAR' UNION ALL
    SELECT 'LAYOUT','VER' UNION ALL
    SELECT 'LAYOUT','EDITAR' UNION ALL
    SELECT 'BASE_DADOS','COMPARAR' UNION ALL
    SELECT 'BASE_DADOS','RESTORE' UNION ALL
    SELECT 'INSTALACAO','VER' UNION ALL
    SELECT 'REGISTRY','EDITAR' UNION ALL
    SELECT 'ESTATISTICAS','VER'
) x
WHERE p.codigo='ADMIN';